apiVersion: apps/v1
kind: Deployment

metadata:
  name: firstdep

spec:
  selector:
    matchLabels:
      app: my-first-pod

  replicas: 3

  template:
    metadata:
      name: my-first-pod
      labels:
        app: my-first-pod
    spec:
      containers:
        - name: os-container
          image: hazemabdo15/projectimage
          ports:
            - containerPort: 8080
